general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# Dim screen 10s before monitors turn off (at 2:50)
listener {
    timeout = 170
    on-timeout = brightnessctl -s set 20%
    on-resume = brightnessctl -r
}

# Turn off monitors at 3 minutes
listener {
    timeout = 180
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Lock screen at 5 minutes
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}
