preload = /home/namit/Downloads/loren-gu-IG1EdbuYCy8-unsplash.jpg

wallpaper {
    monitor = HDMI-A-2
    path = /home/namit/Downloads/loren-gu-IG1EdbuYCy8-unsplash.jpg
    fit_mode = cover
}

splash = false
ipc = off
