#!/usr/bin/env bash

icon="$HOME/dotfiles/scripts/lock_icon.png"
tmpbg='/tmp/screenshot_for_lock_screen.png'

(( $# )) && { icon=$1; }

rm /tmp/screenshot_for_lock_screen*.png
scrot "$tmpbg"
convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
#convert "$tmpbg" "$icon" -gravity center -composite -matte "$tmpbg"
i3lock -u -i "$tmpbg"
